-- Создайте эту таблицу в Supabase Dashboard → SQL Editor
CREATE TABLE processed_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT,
  message_id INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_unique_title ON processed_posts (title);
